"""One-off (2026-09-23): bring every **Summary.** in 0920issues/ in line with SUMMARY_WRITING_GUIDE.md
(three sentences: fact / confusion for the user / "Because ... rather than ..." exposure; <= 130 words; no weakening words)."""
import glob
import os
import re
import sys

ISSUES = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "0920issues")

NEW = {
    "01": "When a tensor that backward needs is modified in place between forward and backward, eager and `aot_eager` raise \"one of the variables needed for gradient computation has been modified by an inplace operation\", while `backend=\"inductor\"` raises nothing for `mm`, `bmm`, `einsum`, `addmm`, 3-D `F.linear` and slicing, and `backward()` returns a gradient computed from the modified input (torch 2.14.0 and nightly, CPU and CUDA). A training loop that reuses its input buffer before `backward()` (`x.copy_(next_batch)`) is stopped by eager, but keeps running under `torch.compile` with gradients of no executed forward pass. Because the saved tensor is a view that Inductor rebuilds with `reinterpret_tensor` rather than the input itself, it no longer shares the input's version counter, and the check disappears for every graph whose backward saves a view of an input.",
    "05": "With `/O1` or `/O2` (with or without `/arch:AVX2` / `/arch:AVX512`), MSVC 19.44.35228 for x64 compiles `_mm256_abs_epi32(_mm256_abs_epi32(v))` to a plain load and store, so negative elements come back unchanged, while `/Od` returns their absolute value; one application and three applications (folded to one) are correct. Any code that applies the intrinsic twice to the same value, directly or after two helper functions are inlined, silently produces negative \"absolute values\". Because the pair is removed as if `pabs*` were an involution like negation (`f(f(x)) == x`) rather than an idempotent operation (`f(f(x)) == f(x)`), the 128-, 256- and 512-bit forms and the 8-, 16- and 32-bit element widths are all affected.",
    "07": "For a function whose output is `x / temperature`, `buf * momentum` or `x + bias` called with the neutral value (`1.0`, `1.0`, `0`), eager and `aot_eager` return a fresh tensor, while Inductor returns the input object itself (`out is x`; with `requires_grad`, another object on the same storage), on torch 2.14.0 and nightly, CPU and CUDA. A caller that then updates the result in place (`new_buf.add_(g)`, `logits.clamp_(...)`) overwrites its own input with no error, only for the value that makes the operation a no-op: the same code is correct for `temperature=0.9` and wrong for `temperature=1.0`. Because `joint_graph.remove_no_ops` replaces the node by its operand without the check that `post_grad.remove_noop_ops` has (\"Don't introduce new aliasing between inputs and outputs\"), every graph that returns such a no-op of an input is affected.",
    "08": "For an FX node `operator.pow(-2, x)`, `torch.fx.Interpreter` computes `(-2) ** x`, while the Python source that `GraphModule` generates is `pow_1 = -2 ** x`, which Python parses as `-(2 ** x)`, so `gm(2)` returns `-4` instead of `4` (torch 2.14.0 and nightly). Any program that raises a negative constant to a traced power silently gets the wrong sign for even exponents: under `torch.compile(dynamic=True)` with `backend=\"eager\"` or `\"aot_eager\"`, the alternating-sign idiom `x * (-1) ** x.shape[0]` returns `-x` for every length, and `torch.fx.symbolic_trace` is wrong too. Because the code generator formats the template `\"{} ** {}\"` with the plain `repr` of each argument rather than parenthesising it, and `**` binds tighter than unary minus, every negative literal used as the base of `pow` is affected.",
    "09": "`a // b`, `torch.floor_divide` and `torch.div(..., rounding_mode=\"floor\")` on floating-point tensors do not agree between eager and Inductor when the exact quotient lies just below an integer: for `1.0 // 0.1` eager returns `9.0`, as Python does, and Inductor returns `10.0`; the same happens for `0.5 // 0.1` and `6.0 // 0.2` in float32 and float64 (torch 2.14.0 and nightly, CPU and CUDA, Windows and Linux; `aot_eager` matches eager). A user who bins values or computes indices with `//` gets a bucket that is one too high after adding `torch.compile`, with no warning. Because Inductor lowers floating floor division to `floor(div_rn(a, b))` rather than to eager's fmod-based algorithm, every quotient that rounds up to an integer in floating point is affected, on every device that shares this lowering.",
    "10": "When a compiled function instantiates a locally defined class and calls a method that mutates a list or dict captured from the enclosing scope, eager mutates it on every call and `torch.compile` never does: `list.append`, `dict[k] = v` and `dict[k] += 1` leave the container unchanged, while the tensor result is correct (torch 2.14.0 and nightly; `backend=\"eager\"` with `fullgraph=True` is enough). A helper object that counts calls or records shapes leaves an empty log after compiling, with no graph break and no error, and a context manager written this way loses its state. Because the mutation is replayed correctly when the object is created outside the compiled function or a nested function is used rather than a method, the loss is specific to method closures of objects created while tracing.",
    "12": "Five NumPy functions do not agree between CPython + NumPy and the same code under `torch.compile`, where Dynamo translates them to `torch._numpy`: `np.fix(1.5)` returns `2.0` instead of `1.0`, `np.cbrt(-8.0)` returns `nan` instead of `-2.0`, `np.clip(int8_array, -1000, 1000)` returns `-24` for every element, `np.clip(uint8_array, -2, 5)` returns `5` for every element, and `np.sign(nan)` / `np.heaviside(nan, h)` return `0.0` instead of `nan` (torch 2.14.0 and nightly; `backend=\"eager\"` is enough). A user who decorates a working NumPy function with `torch.compile` gets different numbers with no warning and no graph break. Because the divergence is decided inside `torch._numpy` (`fix` is an alias of `torch.round`, `cbrt` is `torch.pow(x, 1/3)`, `clip` forwards out-of-range Python integers to `torch.clamp`) rather than by the backend, every compiled NumPy program that calls these functions is affected.",
    "13": "`torch.remainder` and `%` on float tensors do not agree between eager and CPU Inductor once the tensor is vectorized: with a divisor of `±inf` eager returns the dividend and Inductor returns `nan`, and `1e20 % 3.0` is `2.0` in eager and `0.0` under Inductor, while a 3-element tensor takes the scalar tail and is correct (torch 2.14.0 and nightly, Windows and Linux; `aot_eager`, `torch.fmod` and CUDA match eager). A user sees values change, even to NaN, once the batch reaches eight elements, which looks like a data issue. Because the vector path computes `a - floor_divide(a, b) * b` rather than the `fmod` with sign correction of the scalar path and eager, every vectorized float remainder with a large quotient or an infinite divisor is affected.",
    "16": "With `torch._dynamo.config.capture_scalar_outputs = True`, `v = loss.item()` is an unbacked SymFloat and the self-comparison `v != v` is simplified to `False` while tracing, so for a NaN loss eager takes the `if v != v:` branch and the compiled function takes the other one on every backend (torch 2.14.0 and nightly). A training step that skips the update when the loss is NaN, written with the standard `x != x` idiom, applies the NaN update after compilation, with no error and no recompilation. Because the symbol is simplified as a finite real rather than as an IEEE float, `v != v` becomes false and `v - v` and `v * 0` become `0`, so every simplification that does not hold for NaN or infinity is affected, while `math.isnan(v)` stays correct.",
    "17": "With `/O1` or `/O2`, MSVC 19.44.35228 for x64 compiles `_mm256_add_ps(x, _mm256_setzero_ps())` to a plain load and store, so an element `-0.0` comes back as `-0.0`, whereas `-0.0 + (+0.0)` is `+0.0` and `/Od` returns that; the fold is applied under the default `/fp:precise` and under `/fp:strict` as well. Code that relies on the addition to normalise the zero before `1/x` or `signbit` gets the other sign only in optimised builds. Because the fold `x + 0.0 → x` is made by the intrinsic simplifier rather than by the scalar optimizer, which keeps the `addss` of `float f(float x) { return x + 0.0f; }` in the same build, the `ps` and `pd` additions of all three widths are affected, with the zero on either side, as `setzero` or `set1(0.0f)`.",
    "18": "The select `(x <= y) ? y : x`, written as `_mm_blendv_ps(x, y, _mm_cmp_ps(x, y, _CMP_LE_OS))`, returns `y` when the operands compare equal, so for `x = +0.0, y = -0.0` it returns `-0.0` at `/Od`; with `/O1` or `/O2` and `/arch:AVX2` or `/arch:AVX512`, MSVC 19.44.35228 replaces the compare-and-blend pair by `vmaxps y, x`, which returns `x` (`+0.0`) on equality, and `/fp:strict` does not disable the fold. Code that selects between zeros of opposite sign gets the other zero only in optimised VEX-encoded builds (256-bit code already at plain `/O2`). Because predicates that include equality (`_CMP_LE_OS`, `_CMP_GE_OS`, `_CMP_NLE_US`) are folded like the strict ones rather than kept as compare and blend, the `ps` / `pd`, `blendv` and AVX-512 `mask_blend` forms are all affected, `_CMP_NLE_US` even in the SSE encoding.",
    "19": "NumPy code compiled with `torch.compile` does not follow NumPy's result-type and result-shape rules in several common functions: `np.cumsum` / `np.cumprod` of an int8 array stay int8 and overflow where NumPy accumulates in int64, `np.square` / `np.reciprocal` of an integer array return float64, `int8 / int8` returns float32, `np.sum(uint8)` returns int64, `np.any(uint8)` returns uint8 instead of bool, `np.median` / `np.percentile` / `np.quantile` return shape `(1,)` instead of a scalar, and arithmetic on uint16/uint32/uint64 arrays raises `NotImplementedError` (torch 2.14.0 and nightly, `backend=\"eager\"`). A user sees a running total that silently wraps at 127, a downstream `if result:` that changes behavior, or a function that stops working once compiled. Because these rules are decided inside `torch._numpy` rather than by the backend, every compiled NumPy program that uses small integer dtypes is exposed.",
}

WEAK = r"\b(seems?|might|I think|we|our|critical|severe|dangerous|malicious|attack|probably|perhaps|appears? to|likely)\b"
apply = "--apply" in sys.argv
ok = True
for f in sorted(glob.glob(os.path.join(ISSUES, "[0-9][0-9]-*.md"))):
    num = os.path.basename(f)[:2]
    s = open(f, encoding="utf-8").read()
    if "## Comment" in s:
        continue
    m = re.search(r"(\*\*Summary\.\*\* )(.*?)(\n\n)", s, re.S)
    para = NEW.get(num, m.group(2).strip())
    t = re.sub(r"\([^()]*\)", "P", re.sub(r"`[^`]*`", "C", para))
    sents = [x for x in re.split(r"(?<=\.)\s+(?=[A-Z])", t) if x.strip()]
    n = len(para.split())
    good = n <= 130 and len(sents) == 3 and sents[2].startswith("Because") and not re.search(WEAK, para, re.I)   # "rather than" is the guide's model phrasing, not a rule
    ok &= good
    print(num, "words", n, "sentences", len(sents), "because+rather-than", sents[2].startswith("Because") and " rather than " in sents[2] or " rather than " in para, "OK" if good else "<<< FIX")
    if apply and num in NEW:
        open(f, "w", encoding="utf-8").write(s[:m.start(2)] + para + s[m.end(2):])
print("all ok" if ok else "NOT ok", "| applied" if apply else "| dry run")
